apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: app-elected-api
  name: app-elected-api
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
